<?php
$this->title = "";
$this->headTitle($this->title);
?>

<style>
    .filter {
        position: sticky;
        top: 50px;
    }
</style>



<?php

if(isset($_GET['page']) && !empty($_GET['page'])){
    $currentPage = ($_GET['page']);
}else{
    $currentPage = 1;
}


$nbpays = sizeof($this->dataPays);
$parPage = 12;
// On calcule le nombre de pages total
$pages = ceil($nbpays / $parPage);
// Calcul du 1er article de la page
$premier = ($currentPage * $parPage) - $parPage;

?>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-2">
            <form class="filter mt-5" method="POST">
                <div class="form-group">
                    <input name="search" class="form-control mr-sm-2" type="search" placeholder="Recherche"aria-label="Search">
                </div>
                <fieldset class="form-group">
                    <legend class="col-form-label">Continents</legend>
                    <?php foreach ($this->data as $a){ ?>
                    <div class="form-check">
                        <label class="form-check-label">
                        <input class="form-check-input" type="checkbox" name="continents[]" value=<?=$a->_sCode?>>
                        <?=$a->_sName?></label>
                    </div>
                    <?php } ?>
                </fieldset>
                <button class="btn btn-primary btn-block btn-sm" type="submit">Appliquer</button>
            </form>
        </div>

<?php

$this->dataPays=array_slice($this->dataPays, $premier, $parPage);

?>

        <div class="col-lg-10">
        <div class="row d-flex justify-content-center mt-4">
            <nav>
                <ul class="pagination">
                    <!-- Lien vers la page précédente (désactivé si on se trouve sur la 1ère page) -->
                    <li class="page-item <?= ($currentPage == 1) ? "disabled" : "" ?>">
                        <a href="?page=<?= $currentPage - 1 ?>" class="page-link">Précédente</a>
                    </li>
                    <?php
                        for($page = $currentPage>5 ? $currentPage-4 : 1; $page <= ($currentPage<$pages ? $currentPage+4 : $pages); $page++){
                        ?>
                        <!-- Lien vers chacune des pages (activé si on se trouve sur la page correspondante) -->
                        <li class="page-item <?= ($currentPage == $page) ? "active" : "" ?>">
                            <a href="?page=<?= $page ?>" class="page-link"><?= $page ?></a>
                        </li>
                    <?php
                    }
                    
                    ?>
                        <!-- Lien vers la page suivante (désactivé si on se trouve sur la dernière page) -->
                        <li class="page-item <?= ($currentPage == $pages) ? "disabled" : "" ?>">
                        <a href="?page=<?= $currentPage + 1 ?>" class="page-link">Suivante</a>
                    </li>
                </ul>
            </nav>
        </div>
            <div class="row">
                <?php foreach ($this->dataPays as $a) { ?>
                    <div class="col-lg-3 mb-4 mt-4">
                        <div class="card mb-3 shadow-lg mb-5 bg-white rounded" style="height: 410px;">
                        <img class="card-img-top" style="max-height:143px; height:143px" src=<?=$a->_sCountryFlag?> alt="Card image cap">
                            <div class="card-header font-weight-bold"><?=$a->_sName?></div>
                            <div class="card-body text-dark">
                                <p><b>Capitale:</b> <?=$a->_sCapitalCity?></p>
                                <p style="font-size: 14px;"><b>Phone Code:</b> <?=$a->_sPhoneCode?></p>
                                <p style="font-size: 14px;"><b>Langages:</b>
                                <?php
                                    foreach($a->_language as $l) {
                                        echo $l->sName;
                                    }
                                    ?>
                                <p style="font-size: 14px;"><b>Continent:</b> <?=$a->_CCode?>
                                </p>
                            </div>
                        </div>
                    </div>
                <?php } ?>
            </div>
            <div class="row d-flex justify-content-center mb-4">
            <nav>
                <ul class="pagination">
                    <!-- Lien vers la page précédente (désactivé si on se trouve sur la 1ère page) -->
                    <li class="page-item <?= ($currentPage == 1) ? "disabled" : "" ?>">
                        <a href="?page=<?= $currentPage - 1 ?>" class="page-link">Précédente</a>
                    </li>
                    <?php
                        for($page = $currentPage>5 ? $currentPage-4 : 1; $page <= ($currentPage<$pages ? $currentPage+4 : $pages); $page++){
                        ?>
                        <!-- Lien vers chacune des pages (activé si on se trouve sur la page correspondante) -->
                        <li class="page-item <?= ($currentPage == $page) ? "active" : "" ?>">
                            <a href="?page=<?= $page ?>" class="page-link"><?= $page ?></a>
                        </li>
                    <?php
                    }
                    
                    ?>
                        <!-- Lien vers la page suivante (désactivé si on se trouve sur la dernière page) -->
                        <li class="page-item <?= ($currentPage == $pages) ? "disabled" : "" ?>">
                        <a href="?page=<?= $currentPage + 1 ?>" class="page-link">Suivante</a>
                    </li>
                </ul>
            </nav>
        </div>
        </div>
    </div>
</div>