<?php
$this->title = "";
$this->headTitle($this->title);
?>

<style>
    .filter {
        position: sticky;
        top: 50px;
    }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-2">
            <form class="filter mt-5" method="POST">
                <div class="form-group">
                    <input name="search" class="form-control mr-sm-2" type="search" placeholder="Recherche"aria-label="Search">
                </div>
                <fieldset class="form-group">
                    <legend class="col-form-label">Continents</legend>
                    <?php foreach ($this->data as $a){ ?>
                    <div class="form-check">
                        <label class="form-check-label">
                        <input class="form-check-input" type="checkbox" name="continents[]" value=<?=$a->_sCode?>>
                        <?=$a->_sName?></label>
                    </div>
                    <?php } ?>
                </fieldset>    
                <button class="btn btn-primary btn-block btn-sm" type="submit">Appliquer</button>
            </form>
        </div>
        <div class="col-lg-10">
            <div class="row">
                <?php foreach ($this->dataPays as $a) { ?>
                    <div class="col-lg-3 mb-4 mt-4">
                        <div class="card mb-3 shadow-lg mb-5 bg-white rounded" style="height: 410px;">
                        <img class="card-img-top" style="max-height:143px; height:143px" src=<?=$a->_sCountryFlag?> alt="Card image cap">
                            <div class="card-header font-weight-bold"><?=$a->_sName?></div>
                            <div class="card-body text-dark">
                                <p><b>Capitale:</b> <?=$a->_sCapitalCity?></p>
                                <p style="font-size: 14px;"><b>Phone Code:</b> <?=$a->_sPhoneCode?></p>
                                <p style="font-size: 14px;"><b>Langages:</b>
                                <?php
                                    foreach($a->_language as $l) {
                                        echo $l->sName;
                                    }
                                    ?>
                                <p style="font-size: 14px;"><b>Continent:</b> <?=$a->_CCode?>
                                </p>
                            </div>
                        </div>
                    </div>
                <?php } ?>    
            </div>
        </div>
    </div>
</div>