<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Tutoriel Zend Framework');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
  <head>
      <?php echo $this->HeadMeta(); ?>
      <?php echo $this->headTitle(); ?>
      <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/yeti/bootstrap.min.css" integrity="sha384-mLBxp+1RMvmQmXOjBzRjqqr0dP9VHU2tb3FK6VB0fJN/AOu7/y+CAeYeWJZ4b3ii" crossorigin="anonymous">
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="<?=$this->url(array('action'=>'index'))?>">HOME</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor03">
          <ul class="navbar-nav mr-auto">
          <li class="nav-item">
              <a class="nav-link" href="<?=$this->url(array('action'=>'countries'))?>">Liste des continents</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="<?=$this->url(array('action'=>'countries'))?>">Liste des pays</a>
          </li>
          </ul>
      </div>
    </nav>
    <div class="container-fluid">
      <?=$this->layout()->content?>
    </div>    
  </body>
</html>